### ISSUE TITLE
Scaffold Front End!

### ISSUE THREAD

**Issue by OccultParrot** [OccultParrot/Tomogatch.ai#3]
- Use Tailwind to style it!
- Remember [these](https://github.com/OccultParrot/Tomogatch.ai/tree/main/documentation/assets)

**Comment by OccultParrot** [comment]
Use Tailwind for styling!!!

**Comment by savevsgames** [comment]
I've got the initial set of cats for "cat 1" complete and Ive made them available on slack. I'm working on polishing them a little and then adding color and theme variations. Once the cats look real enough, I'll be starting on the openAI interactions. I chose to do it in that order for two reasons, one, to make the app look polished enough from the start, by giving the front end a custom graphics boost, and second, to give my team a chance to dig in a bit and agree on a project structure and choose what they wanted to work on before trying to force a space for the chat area to exist.
I feel that has set us up well to feel we have time to make the back end our main focus as we near the due date, rather than having to jump and scramble to polish the UI, plus, having some assets to build with from the start makes designing the UI easier. 
Hopefully by early next week we will talking to the cat gpt!
